import { ExpressionNode, QueryNode, SubQueryNode, TableNode } from "../types"

export const checkIsFromTable = (
  value: TableNode | SubQueryNode,
): value is TableNode => {
  return Object.hasOwn(value, "name")
}

/**
 * Traverses an expression tree and applies a callback function to each operand and operator.
 *
 * @param expression - The expression tree to traverse, represented by an ExpressionNode.
 * @param callback - A function that takes an operand (string, number, or string[]) and an optional operator (string).
 */
export function traverseExpression(
  expression: ExpressionNode,
  callback: (
    operand:
      | string
      | number
      | boolean
      | null
      | string[]
      | ExpressionNode
      | QueryNode,
    operator?: string,
  ) => void,
): void {
  if (expression === null) return
  if (
    typeof expression.left === "string" ||
    typeof expression.left === "number" ||
    typeof expression.left === "boolean" ||
    expression.left === null
  ) {
    callback(expression.left, expression.operator)
  } else if (
    typeof expression.left === "object" &&
    expression.left &&
    expression.left.type === "expression"
  ) {
    traverseExpression(expression.left, callback)
  }

  if (
    expression.right &&
    typeof expression.right === "object" &&
    !Array.isArray(expression.right) &&
    expression.right.type === "expression"
  ) {
    traverseExpression(expression.right, callback)
  } else if (expression.right) {
    callback(expression.right, expression.operator)
  }
}

/**
 * A monad that applies a builder function to a value if the value is not null or undefined.
 *
 * @param value - The value to be processed, which can be of type T, null, or undefined.
 * @param builder - A function that takes an optional value of type T and returns a string.
 * @returns A string generated by the builder function, or an empty string if the value is null or undefined.
 */
export function applyMaybeClause<T>(
  value: T | null | undefined,
  builder: (value?: T) => string,
): string {
  if ((Array.isArray(value) && !value.length) || typeof value == "undefined")
    return ""
  if (value === null) return builder()
  return builder(value)
}

export function isSafeIdentifier(identifier: string): boolean {
  const functionPattern =
    /^[a-zA-Z_][a-zA-Z0-9_]*\s*\(([^;'"`()]|(\([^()]*\)))*\)$/
  const simpleIdentifier = /^[a-zA-Z_][a-zA-Z0-9_.]*$/

  return simpleIdentifier.test(identifier) || functionPattern.test(identifier)
}
export function isSafeExpressionIdentifier(value: string): boolean {
  const forbidden =
    /[";#`]|--|\b(SELECT|DROP|INSERT|UPDATE|DELETE|EXEC|UNION|CREATE|ALTER|GRANT|REPLACE|TRUNCATE)\b/i
  if (forbidden.test(value)) return false

  // Allow JSON_EXTRACT(json_field, '$.path') and similar functions
  const basicFunctionCall =
    /^[A-Z_][A-Z0-9_]*\s*$begin:math:text$.*$end:math:text$$/i
  const approvedFunctions = [
    "COUNT",
    "MAX",
    "MIN",
    "AVG",
    "SUM",
    "DATE",
    "CAST",
    "COALESCE",
    "JSON_EXTRACT",
    "JSON_VALUE",
    "ROUND",
    "TRIM",
    "LOWER",
    "UPPER",
    "CASE",
    "WHEN",
  ]
  const functionNameMatch = value.match(/^([A-Z_][A-Z0-9_]*)\s*\(/i)

  if (basicFunctionCall.test(value) && functionNameMatch) {
    const fn = functionNameMatch[1].toUpperCase()
    return approvedFunctions.includes(fn)
  }

  return true
}

export function isSafeJoinCondition(expr: ExpressionNode): boolean {
  return !!(
    expr.left &&
    expr.right &&
    typeof expr.left === "string" &&
    typeof expr.right === "string" &&
    expr.left.includes(".") &&
    expr.right.includes(".") &&
    isSafeIdentifier(expr.left.split(".")[0]) &&
    isSafeIdentifier(expr.right.split(".")[0])
  )
}

export function isSafeExpressionANDQueryIdentifier(
  initialQuery: string,
): boolean {
  const unsafePatterns = [
    /;/,
    /--/,
    /\/\*/,
    /\*\//,
    /@@/,
    /char\s*\(/i,
    /nchar\s*\(/i,
    /varchar\s*\(/i,
    /nvarchar\s*\(/i,
    /convert\s*\(/i,
    /exec\s+/i,
    /execute\s+/i,
    /\bunion\b/i,
    /\bdrop\b/i,
    /\binsert\b/i,
    /\bdelete\b/i,
    /\bupdate\b/i,
    /\bcreate\b/i,
    /\balter\b/i,
    /\bshutdown\b/i,
    /\bmerge\b/i,
    /\btruncate\b/i,
    /\bdeclare\b/i,
    /\bset\b/i,
    /\bbegin\b/i,
    /\bif\b/i,
    /\bwhile\b/i,
    /\bloop\b/i,
    /\bexecute\s+immediate\b/i,
    /\bcreate\s+temp\s+function\b/i,
    /\bcreate\s+(or\s+replace\s+)?(table|view|model|function)\b/i,
    /\bdrop\s+(table|view|model|function)\b/i,
    // /`[^`]*`/,
    /\$\w+/,
    /['"`]\s*;\s*\bselect\b/i,
  ]

  return !unsafePatterns.some((p) => {
    if (p.test(initialQuery.toLocaleLowerCase())) {
      console.warn(
        `Unsafe pattern detected in query: ${p.toString()} in "${initialQuery}"`,
      )
    }

    return p.test(initialQuery.toLocaleLowerCase())
  })
}
